language: swift
osx_image: xcode11.7

cache:
  - cocoapods
  - bundler

before_install:
  - gem install cocoapods -v '1.8.4'
  - pod install --repo-update
  - travis_retry brew update
  - brew install swiftlint || true

script:
  - set -o pipefail
  - travis_retry xcodebuild -workspace TrustKeystore.xcworkspace -scheme TrustKeystore -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone X,OS=12.4" test | xcpretty
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
